# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ih0SEHQnNGshP97URTa4kFWaaY3zLuxi
"""

"""
OIP v1.0.28 — Illustrative Decision-Logic & Rank-Shift Audit Demonstration
--------------------------------------------------------------------------
Status: Concept Demonstration (Not Empirical Validation)
Specification: OIP v1.0.28 (Frozen Formulas 1, 2, 4)

This script executes:
1. Blind Evaluation Phase (Using OE, CV, VIS, RC, AFL, CAS)
2. Structural Integrity & Fragility Penalty Adjustment (SIS/FPF)
3. Credential Signal Reintroduction & Rank-Shift Audit (Delta R)
"""

import pandas as pd
import numpy as np

# --- 1. FROZEN MATHEMATICAL FORMULAS ---

def calculate_score_f1(oe: float, cv: float, vis: float) -> float:
    """Formula 1: Score = 0.6*OE + 0.3*CV + 0.1*VIS"""
    return 0.6 * oe + 0.3 * cv + 0.1 * vis

def calculate_sis_f2(rc: float, afl: float, cas: float) -> float:
    """Formula 2: SIS = 0.5*RC + 0.3*AFL + 0.2*CAS"""
    return 0.5 * rc + 0.3 * afl + 0.2 * cas

def calculate_adjusted_sis_f2(sis: float, ids: float) -> float:
    """Formula 2 Addendum: If IDS > 0.7 -> FPF = 1 - IDS -> Adjusted SIS"""
    if ids > 0.7:
        fpf = 1.0 - ids
        return sis * fpf
    return sis

def calculate_liv_f4(ri: float, sr: float, ar: float, ids: float) -> float:
    """
    Formula 4: LIV = (RI * SR * AR) / IDS
    Strict Rule: If IDS == 0, raise ZeroDivisionError. No arbitrary epsilon floors.
    """
    if ids == 0.0:
        raise ZeroDivisionError("OIP Specification Error: IDS cannot be zero in LIV calculation.")
    return (ri * sr * ar) / ids


# --- 2. BLIND EVALUATION & RANK-SHIFT AUDIT DEMONSTRATION ---

def run_rank_shift_audit():
    # Synthetic Multi-Candidate Dataset
    candidates = [
        {
            "id": "Entity_A",
            "CS": 0.95, "DD": 0.90,  # Credentials & Documentation Metadata (Hidden during Step 1)
            "OE": 0.35, "CV": 0.30, "VIS": 0.85, # Outcome & Context Signals
            "RC": 0.40, "AFL": 0.25, "CAS": 0.80, "IDS": 0.82
        },
        {
            "id": "Entity_B",
            "CS": 0.30, "DD": 0.20,  # Credentials & Documentation Metadata (Hidden during Step 1)
            "OE": 0.88, "CV": 0.82, "VIS": 0.40, # Outcome & Context Signals
            "RC": 0.85, "AFL": 0.80, "CAS": 0.35, "IDS": 0.30
        },
        {
            "id": "Entity_C",
            "CS": 0.70, "DD": 0.65,
            "OE": 0.65, "CV": 0.60, "VIS": 0.50,
            "RC": 0.60, "AFL": 0.55, "CAS": 0.50, "IDS": 0.50
        }
    ]

    # Step 1: Blind OIP Evaluation (Evaluating solely on Outcome/Resilience Signals)
    audit_data = []
    for c in candidates:
        f1_score = calculate_score_f1(c["OE"], c["CV"], c["VIS"])
        raw_sis = calculate_sis_f2(c["RC"], c["AFL"], c["CAS"])
        adj_sis = calculate_adjusted_sis_f2(raw_sis, c["IDS"])

        audit_data.append({
            "Entity ID": c["id"],
            "Credential Signal (CS)": c["CS"],
            "Documentation (DD)": c["DD"],
            "OIP Blind Score (F1)": round(f1_score, 4),
            "OIP Adjusted SIS (F2)": round(adj_sis, 4),
            "OIP Combined Index": round(0.7 * f1_score + 0.3 * adj_sis, 4)
        })

    df = pd.DataFrame(audit_data)

    # Step 2: Rank Shift Analysis (Comparing Blind Rank vs Credential Rank)
    df["Credential Rank (CS Heavy)"] = df["Credential Signal (CS)"].rank(ascending=False, method='min').astype(int)
    df["OIP Blind Rank"] = df["OIP Combined Index"].rank(ascending=False, method='min').astype(int)

    # Calculate Rank Shift (Delta R)
    df["Rank Shift (Delta R)"] = df["Credential Rank (CS Heavy)"] - df["OIP Blind Rank"]

    print("=================================================================================")
    print("      OIP v1.0.28 — Blind Evaluation & Rank-Shift Audit (Demonstration)         ")
    print("=================================================================================")
    print(df[["Entity ID", "OIP Blind Score (F1)", "OIP Adjusted SIS (F2)", "Credential Rank (CS Heavy)", "OIP Blind Rank", "Rank Shift (Delta R)"]].to_string(index=False))
    print("=================================================================================")
    print("\nNOTE: This script demonstrates how OIP's blind outcome evaluation shifts ranking")
    print("relative to raw credential signals. Empirical validation (E1-E3) remains pending.")

if __name__ == "__main__":
    run_rank_shift_audit()
