# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BqhXrvq7d7Vdg3MFQSHf-MGIUXV75kB
"""

# oip_reference.py (Final Corrected Implementation Sanity Check)

class OIPReferenceModel:
    def __init__(self):
        self.score_weights = (0.6, 0.3, 0.1)
        self.sis_weights = (0.5, 0.3, 0.2)
        self.stress_weights = (0.1, 0.9)

    def calculate_ii(self, ids: float) -> float:
        return 1.0 - ids

    def calculate_liv(self, ri: float, sr: float, ar: float, ids: float) -> float:
        if ids == 0:
            raise ZeroDivisionError("LIV is undefined for IDS = 0.")
        return (ri * sr * ar) / ids

    def calculate_score(self, oe: float, cv: float, vis: float) -> float:
        w1, w2, w3 = self.score_weights
        return (w1 * oe) + (w2 * cv) + (w3 * vis)

    def calculate_sis(self, rc: float, afl: float, cas: float) -> float:
        w1, w2, w3 = self.sis_weights
        return (w1 * rc) + (w2 * afl) + (w3 * cas)

    def calculate_is(self, sd: float, cw: float) -> float:
        w1, w2 = self.stress_weights
        return (w1 * sd) + (w2 * cw)

    def calculate_gfl(self):
        raise NotImplementedError("GFL not specified.")

    def calculate_aml(self):
        raise NotImplementedError("AML not specified.")

# -----------------------------
# Implementation sanity tests (Corrected for Precision)
# -----------------------------
if __name__ == "__main__":
    oip = OIPReferenceModel()
    print("=== OIP v1.0.27 Implementation Sanity Checks ===")

    # Use abs(a - b) < 1e-9 for floating point comparisons
    assert abs(oip.calculate_ii(0.3) - 0.7) < 1e-9
    print("PASS: II = 1 - IDS")

    assert abs(oip.calculate_score(1.0, 1.0, 1.0) - 1.0) < 1e-9
    print("PASS: Formula 1 weighted sum")

    assert abs(oip.calculate_sis(1.0, 1.0, 1.0) - 1.0) < 1e-9
    print("PASS: Formula 2 weighted sum")

    assert abs(oip.calculate_is(1.0, 1.0) - 1.0) < 1e-9
    print("PASS: Stress-model weighted sum")

    assert abs(oip.calculate_liv(1.0, 1.0, 1.0, 0.5) - 2.0) < 1e-9
    print("PASS: Formula 4 normal evaluation")

    try:
        oip.calculate_liv(1.0, 1.0, 1.0, 0.0)
    except ZeroDivisionError:
        print("PASS: Formula 4 IDS=0 boundary correctly exposed")

    try:
        oip.calculate_gfl()
    except NotImplementedError:
        print("PASS: GFL correctly marked unresolved")

    try:
        oip.calculate_aml()
    except NotImplementedError:
        print("PASS: AML correctly marked unresolved")

    print("\nAll implementation sanity checks passed.")
    print("This is NOT empirical validation of the OIP framework.")